Import Libraries

In [1]:
import pandas as pd
import numpy as np

Load Cleaned Datasets

In [2]:
customers = pd.read_csv("../datasets/cleaned/customers_clean.csv")

orders = pd.read_csv(
    "../datasets/cleaned/orders_clean.csv",
    parse_dates=[
        "order_purchase_timestamp",
        "order_estimated_delivery_date"
    ]
)

order_items = pd.read_csv("../datasets/cleaned/order_items_clean.csv")

payments = pd.read_csv("../datasets/cleaned/payments_clean.csv")

Merge Customers and Orders

Customers (1)
      │
customer_id
      │
Orders (N)

In [3]:
customer_orders = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

print(customer_orders.shape)
customer_orders.head()

(96455, 9)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_estimated_delivery_date
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-06-05
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-02-06
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-06-13
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-04-10
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-08-15

Merge Order Items

Orders (1)
      │
order_id
      │
Order Items (N)

In [4]:
customer_orders_items = pd.merge(
    customer_orders,
    order_items,
    on="order_id",
    how="inner"
)

print(customer_orders_items.shape)
customer_orders_items.head()

(110173, 13)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_estimated_delivery_date,order_item_id,product_id,price,freight_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-06-05,1,a9516a079e37a9c9c36b9b78b10169e8,124.99,21.88
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-02-06,1,4aa6014eceb682077f9dc4bffebc05b0,289.00,46.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-06-13,1,bd07b66896d6f1494f5b86251848ced7,139.94,17.79
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-04-10,1,a5647c44af977b148e0a3a4751a09e2e,149.94,23.36
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-08-15,1,9391a573abe00141c56e38d84d7d5b3b,230.00,22.25

Merge Payments

Orders (1)
      │
order_id
      │
Payments (N)

In [5]:
merged_df = pd.merge(
    customer_orders_items,
    payments,
    on="order_id",
    how="inner"
)

print(merged_df.shape)
merged_df.head()

(115011, 16)

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state,order_id,order_status,order_purchase_timestamp,order_estimated_delivery_date,order_item_id,product_id,price,freight_value,payment_type,payment_installments,payment_value
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP,00e7ee1b050b8499577073aeb2a297a1,delivered,2017-05-16 15:05:35,2017-06-05,1,a9516a079e37a9c9c36b9b78b10169e8,124.99,21.88,credit_card,2,146.87
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP,29150127e6685892b6eab3eec79f59c7,delivered,2018-01-12 20:48:24,2018-02-06,1,4aa6014eceb682077f9dc4bffebc05b0,289.00,46.48,credit_card,8,335.48
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP,b2059ed67ce144a36e2aa97d2c9e9ad2,delivered,2018-05-19 16:07:45,2018-06-13,1,bd07b66896d6f1494f5b86251848ced7,139.94,17.79,credit_card,7,157.73
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP,951670f92359f4fe4a63112aa7306eba,delivered,2018-03-13 16:06:38,2018-04-10,1,a5647c44af977b148e0a3a4751a09e2e,149.94,23.36,credit_card,1,173.30
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP,6b7d50bd145f6fc7f33cebabd7e49d0f,delivered,2018-07-29 09:51:30,2018-08-15,1,9391a573abe00141c56e38d84d7d5b3b,230.00,22.25,credit_card,8,252.25

Verify the Merged Dataset

In [6]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 115011 entries, 0 to 115010
Data columns (total 16 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   customer_id                    115011 non-null  object
 1   customer_unique_id             115011 non-null  object
 2   customer_zip_code_prefix       115011 non-null  int64
 3   customer_city                  115011 non-null  object
 4   customer_state                 115011 non-null  object
 5   order_id                       115011 non-null  object
 6   order_status                   115011 non-null  object
 7   order_purchase_timestamp       115011 non-null  datetime64[ns]
 8   order_estimated_delivery_date  115011 non-null  datetime64[ns]
 9   order_item_id                  115011 non-null  int64
 10  product_id                     115011 non-null  object
 11  price                          115011 non-null  float64
 12  freight_value                  115011 non-null  float64
 13  payment_type                   115011 non-null  object
 14  payment_installments           115011 non-null  int64
 15  payment_value                  115011 non-null  float64
dtypes: datetime64[ns](2), float64(3), int64(3), object(8)
memory usage: 14.0+ MB

In [7]:
merged_df.isnull().sum()

customer_id                      0
customer_unique_id               0
customer_zip_code_prefix         0
customer_city                    0
customer_state                   0
order_id                         0
order_status                     0
order_purchase_timestamp         0
order_estimated_delivery_date    0
order_item_id                    0
product_id                       0
price                            0
freight_value                    0
payment_type                     0
payment_installments             0
payment_value                    0
dtype: int64

In [8]:
merged_df.duplicated().sum()

np.int64(670)

Save the Merged Dataset

In [10]:
merged_df.to_csv(
    "../datasets/cleaned/merged_customer_data.csv",
    index=False
)

print("Merged dataset saved successfully!")

Merged dataset saved successfully!

## Dataset Merging

The cleaned datasets were merged using the following keys:

- Customers ↔ Orders using `customer_id`
- Orders ↔ Order Items using `order_id`
- Orders ↔ Payments using `order_id`

The resulting merged dataset contains customer details, order information, product prices, freight costs, and payment details in a single table. This consolidated dataset will be used for feature engineering and customer segmentation.